language: smalltalk
sudo: false

os:
  - linux
  - osx

smalltalk:
  - Squeak-trunk
  - Squeak-5.1

  
email:
    recipients:
      - swt-team8-travis@lists.myhpi.de
    on_success: change
    on_failure: always
